    // alchemy
    {  0, {  1, 0x1000}}, // Acid Rain
    {  1, {  1, 0x1001}}, // Atlas
    {  2, {  1, 0x1002}}, // Barrier
    {  3, {  1, 0x1003}}, // Call Up
    {  4, {  1, 0x1004}}, // Corrosion
    {  5, {  1, 0x1005}}, // Crush
    {  6, {  1, 0x1006}}, // Cure
    {  7, {  1, 0x1007}}, // Defend
    {  8, {  1, 0x1008}}, // Double Drain
    {  9, {  1, 0x1009}}, // Drain
    { 10, {  1, 0x100a}}, // Energize
    { 11, {  1, 0x100b}}, // Escape
    { 12, {  1, 0x100c}}, // Explosion
    { 13, {  1, 0x100d}}, // Fireball
    { 14, {  1, 0x100e}}, // Fire Power
    { 15, {  1, 0x100f}}, // Flash
    { 16, {  1, 0x1010}}, // Force Field
    { 17, {  1, 0x1011}}, // Hard Ball
    { 18, {  1, 0x1012}}, // Heal
    { 19, {  1, 0x1013}}, // Lance
    { 20, {  1, 0x1015}}, // Levitate
    { 21, {  1, 0x1016}}, // Lightning Storm
    { 22, {  1, 0x1017}}, // Miracle Cure
    { 23, {  1, 0x1018}}, // Nitro
    { 24, {  1, 0x1019}}, // One Up
    { 25, {  1, 0x101a}}, // Reflect
    { 26, {  1, 0x101b}}, // Regrowth
    { 27, {  1, 0x101c}}, // Revealer
    { 28, {  1, 0x101d}}, // Revive
    { 29, {  1, 0x101e}}, // Slow Burn
    { 30, {  1, 0x101f}}, // Speed
    { 31, {  1, 0x1020}}, // Sting
    { 32, {  1, 0x1021}}, // Stop
    { 33, {  1, 0x1022}}, // Super Heal
